app/config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'

  match '/destroy_session', to: 'sessions#destroy', via: :get, method: :delete
  get '/auth/:provider/callback', to: 'sessions#create'

  resources :rants, only: [:new, :create]
  resources :sessions, only: [:create, :destroy]
end

app/app/models/rant.rb
class Rant < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :body, presence: true

  before_create :post_to_twitter

  def post_to_twitter
    # This will make call to RantReverse service
    final_arr = RantReverse.call body

    final_arr.each do |body|
      user.twitter.update body
    end
  end
end

app/app/models/user.rb
class User < ActiveRecord::Base

  has_many :rants, inverse_of: :user, dependent: :destroy

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash[:provider],
                 uid: auth_hash[:uid]).first_or_create
    user.update(
      nickname: auth_hash[:info][:nickname],
      profile_image: auth_hash[:info][:profile_image],
      token: auth_hash[:credentials][:token],
      secret: auth_hash[:credentials][:secret]
    )
    user
  end

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      if Rails.env.development? || Rails.env.test?
        config.consumer_key = Rails.application.secrets.twitter_api_key
        config.consumer_secret = Rails.application.secrets.twitter_api_secret
      else
        config.consumer_key = ENV["TWITTER_API_KEY"]
        config.consumer_secret = ENV["TWITTER_API_SECRET"]
      end
      config.access_token = token
      config.access_token_secret = secret
    end
  end
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :set_rant, only: [:show, :edit, :update, :destroy]

  rescue_from Exception, with: :rant_rescue

  def index
    @rants = Rant.all
  end

  def show
  end

  def new
    @rant = Rant.new
  end

  def create
    begin
      @rant = Rant.new(rant_params)

      if current_user.nil?
        flash[:errors] = "You need to log in first"
        render action: :new
        return
      end

      @rant.user_id = current_user.id
      @rant.save

      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  end

  private

  def set_rant
    @rant = Rant.find(params[:id])
  end

  def rant_params
    params.require(:rant).permit(:user_id, :body)
  end

  def rant_rescue(e = nil)
    flash[:errors] = e.message if e
    render action: :new
  end

end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id

    respond_to do |format|
      format.html
        if @user.valid?
          redirect_to new_rant_path
          return
        end
      redirect_to root_path
    end

  end

  def destroy
    reset_session
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/app/views/homes/index.html.erb
<div class="col col-md-8 col-md-offset-2">
<h2 class="text-center">Rantr is the easiest way to post long tweets. <br /><br />Just <a href="/auth/twitter">LOGIN</a>, type your thoughts, and rant!</h2>

<br />
<br />
<br />
<br />
<br />
<h4 class="text-center">Made with &#9829; by <a target="_blank" href='https://twitter.com/gravescollin'>@gravescollin</a> in about 20 minutes.</h4>
</div>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/navbar" %>
<%= render partial: "shared/flash_messages", flash: flash %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Rantr (alpha)', root_path, class: 'navbar navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'New Rant', new_rant_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
          <% if current_user %>
            @<%= current_user.nickname %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">My Rants</a></li>
              <li><a href="#">Settings</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', destroy_session_path %></li>
          <% else %>
            <li><a href="/auth/twitter">Login</a></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/app/views/rants/_form.html.erb
<%= form_for(@rant) do |f| %>
  <% if @rant.errors.any? %>
    <div class="errors">
      <h2><%= pluralize(@rant.errors.count, "error") %> screwed up the posting of this rant</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, rows: 10, placeholder: "Type your rant here and we'll handle the rest. Make sure you've logged in! (Your Twitter handle will be in the upper-right corner)" %>
  </div>
  <div class="actions">
    <%= f.submit 'Rant!', class: 'btn btn-primary'  %>
  </div>
<% end %>

app/app/views/rants/new.html.erb
<div class="col col-md-4 col-md-offset-4">
  <span class="text-center"><h1>New Rant!</h1></span>
  <br />

  <%= render 'form' %>
</div>

app/app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <span class='verbiage'><%= message %></span>
  </div>
<% end %>